services:
  - type: web
    name: agm-pro
    env: static
    rootDir: src/frontend
    buildCommand: pnpm install --no-frozen-lockfile && pnpm build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_USE_MOCK
        value: "true"
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
